CREATE TABLE USERINFO  (
		  USERID VARCHAR(90) NOT NULL , 
		  PASSWORD VARCHAR(20) NOT NULL , 
		  USERNAME VARCHAR(80) NOT NULL , 
		  DOB VARCHAR(15) NOT NULL , 
		  GENDER VARCHAR(6) NOT NULL , 
		  CONTACT VARCHAR(15) NOT NULL , 
		  CITY VARCHAR(60) NOT NULL , 
		  STATUS VARCHAR(10) NOT NULL , 
		  LIP VARCHAR(15) NOT NULL , 
		  UC INTEGER NOT NULL ) ; 

ALTER TABLE USERINFO 
	ADD CONSTRAINT CC1494503778962 PRIMARY KEY
		(USERID);
 

CREATE TABLE PRODUCTS  (
		  PID INTEGER NOT NULL , 
		  PTITLE VARCHAR(100) NOT NULL , 
		  CATEGORY VARCHAR(20) NOT NULL , 
		  MPRC VARCHAR(10) NOT NULL , 
		  OPRC VARCHAR(10) NOT NULL , 
		  DESCRIPTION VARCHAR(3000) NOT NULL );

ALTER TABLE PRODUCTS 
	ADD CONSTRAINT CC1494930346444 PRIMARY KEY
		(PID);
